### PIPELINE INPUT ###

pro_corr_lr_bam: "" # Input corrected long reads for the proband to assemble in BAM format
pro_corr_lr_fq: "" # Input corrected long reads for the proband to assemble in FASTQ format

pro_sr_bam: "" # Input short reads for the proband to assemble in BAM format
pro_sr_fq: "" # Input short reads for the proband to assemble in FASTQ format. IMPORTANT: This *MUST* be an interleaved FASTQ file!

pat_sr_bam: "" # Input paternal short reads in BAM format
pat_sr_fq: "" # Input paternal short reads in FASTQ format

mat_sr_bam: "" # Input maternal short reads in BAM format
mat_sr_fq: "" # Input maternal short reads in BAM format

out_dir: "" # Output directory

# Size of the genome to assemble in bp (for long reads subsampling), e.g. 3100000000 for human.
# Only use if input long read coverage is >50x
# Default value is -1 (no subsampling)
genome_size: -1

# Maximum base quality of the input long reads
# This pipeline is designed for ONT R9.4 long reads for which the maximum base quality is 40.
# However, ONT R10 long read data may use a maximum base quality of 90.
max_lr_bq: 40

### PIPELINE CONFIG ###

# This pipeline uses default models trained on ONT R9.4 long reads corrected with Illumina for Pepper-Margin-DeepVariant r0.7
# These models are assumed to be available by default in pmdv/r07/models/ratatosk_r9_guppy5_sup
# However, it is possible to supply here your own models which will override the default ones
# Make sure to leave empty in order to use the default models
pmdv_r07_model_r9_guppy5_sup_snp: ""
pmdv_r07_model_r9_guppy5_sup_hp: ""
pmdv_r07_model_r9_guppy5_sup_dv: ""


